<div class="">
    <div>
        <h2>Sign In</h2>
        <hr/>
    </div>
    <form role="form" method="post" action="./api/authority/">
        <div class="form-group">
            <label for="email">Email</label>
            <input class="form-control" type="email" name="email" required placeholder="Email Address"/>        
            <p class="help-block">
                A valid email address is required to sign in.
            </p>
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input class="form-control" type="password" name="password" required placeholder="Your Password"/>
            <p class="help-block">
                Enter your password
            </p>
        </div>
        <div class="form-group pull-right">
            <button type="button" class="cancel btn btn-inverse" title="This is not where I want to be">Cancel</button>
            <button type="submit" class="btn btn-inverse" title="I am back">Sign In</button>
        </div>
    </form>
</div>