<!DOCTYPE html>
<html lang="en-us">
	<head>
		<meta name="description" content="Created by Kore9 v<?=getVersion();?>">
		<meta name="keywords" content="kore9 v<?=getVersion();?>">
		<meta name="author" content="Kore9 - VisionMise">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta charset="UTF-8">
		<link rel="stylesheet" href="assets/css/normalize.css"/>
		<link rel="stylesheet" href="assets/css/bootstrap.min.css"/>
		<link rel="stylesheet" href="assets/css/bootstrap-theme.min.css"/>
		<link rel="stylesheet" href="assets/css/kore9.css"/>
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
		<script src="assets/js/bootstrap.min.js"></script>
		<script src="assets/js/rame.js"></script>
		<script src="assets/js/kore9.ui.js"></script>
		<script src="assets/js/kore9.init.js"></script>
	</head>
	<body>
		<div class="space"></div>
		<div class="container">
		    <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2">
		        <div class="panel panel-default">
		            <div class="panel-heading">
		                <h3 class="title lg text-muted">
		                    Kore9 Installation
		                    <small class="">
		                        v<?=getVersion();?>
		                    </small>
		                </h3>
		            </div>
		            <div class="panel-body">
		                <div id="signin">
		                    <div id="register">
		                        <div id="about">
		                            <h4>Database Connection</h4>
		                            <div>
		                                <p>
		                                	Welcome.
		                                	<br/>
		                                	A database connection needs setup. Please use
		                                	the form below to enter the required information.
		                                </p>
		                            </div>
		                            <hr/>
		                        </div>
		                    </div>
		                </div>
		            </div>
		        </div>
		        <a href="javascript:void(0);" class="a_credits" title="What?">
		            <small class="pull-right text-muted">
		                Kore9 version <?=getVersion();?>
		            </small>
		        </a>
		    </div>
		</div>
	</body>
</html>
