<?php global $userAccount; ?>
<div>
	<h4>
		<?=$userAccount['username'];?>
		<small>Character Type</small>
	</h4>
	<div>
		<div class="row">

			<div class="col-lg-6 col-md-6 col-sm-6 col-xl-6">
				<table class="table">
					<caption class="l">
						Background
					</caption>
					<tbody>
						<tr>
							<th>Age</th>
							<td class="r">0 Yrs</td>
						</tr>
						<tr>
							<th>Level</th>
							<td class="r">0</td>
						</tr>
						<tr>
							<th>XP</th>
							<td class="r">0</td>
						</tr>
						<tr>
							<th>Origin</th>
							<td class="r">Unknown</td>
						</tr>
						<tr>
							<th>Gender</th>
							<td class="r">None</td>
						</tr>
					</tbody>
				</table>
			</div>

			<div class="col-lg-6 col-md-6 col-sm-6 col-xl-6">
				<table class="table">
					<caption class="l">
						Stats
					</caption>
					<tbody>
						<tr>
							<th>Health</th>
							<td class="r">0</td>
						</tr>
						<tr>
							<th>Magic</th>
							<td class="r">0</td>
						</tr>
						<tr>
							<th>Attack</th>
							<td class="r">0</td>
						</tr>
						<tr>
							<th>Defence</th>
							<td class="r">0</td>
						</tr>
						<tr>
							<th>Resist</th>
							<td class="r">0</td>
						</tr>
					</tbody>
				</table>
			</div>

		</div>

		<div class="r">
			<span>
				<button class="btn btn-sm btn-inverse">Create Character</button>
			</span>
		</div>
	</div>
</div>