<h2>Kore9 Credits</h2>
<hr/>		

<section id="Main Credits">

	<div>	
		<h4>Development</h4>
		<p>
			Kore9 is developed by VisionMise
		</p>
		<p>
			<span class="glyphicon glyphicon-envelope"></span>
			<a href="mailto:visionmise@kuhlonline.com" title="Exchange Communci">
				VisionMise
			</a>
			<br/>
			<span class="glyphicon glyphicon-phone"></span>
			<a href="#sike=what&call=visionmise@on.the.phone&real=no&fake=very+much+so" title="yeah right.. Sorry">
				Call him on the phone
			</a>
		</p>
	</div>

	<hr/>

	<div>	
		<h4>Web / Email Hosting</h4>
		<p>
			Web and Email Hosting provided by Kuhlonline.com
		</p>
	</div>

	<hr/>

	<div>	
		<h4>People</h4>
		<p>
			A very <i>Special Thank You</i> to my Family.
		</p>
	</div>

	<hr/>

	<div>	
		<h4>Technologies</h4>
		<p>
			Many Thanks for
			<br/>
			PHP, MySQL, JavaScript, Twitter Bootstrap 3, and jQuery.
			<br/>
			<br/>
			Also thanks to GNU/Linux
			<br/>
			<br/>
			Thank you Apache for making an amazing http service
			<br/>
			<br/>
			Thank you Google for doing what you do, which makes what I do easier. And
			also for hosting my jQuery Libraries!
			<br/>
			<br/>
			Thank you StackOverflow!!!
			<br/>
			<br/>
			Thank you w3schools.org!
			<br/>
			<br/>
			Thank you GitHub for hosting my code and making the control of it ever so much
			easier.
		</p>
	</div>

	<hr/>

</section>

<button type="button" class="pull-right cancel btn btn-inverse" title="to where I belong...">Go Back</button>