<div class="space"></div>
<div class="container">
    <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="title lg text-muted">
                    Kore9
                    <small class="pull-right">
                        <a href="javascript:void(0);" class="a_signout" title="Sign Out">
                            <span class="lg glyphicon glyphicon-remove"></span>
                        </a>
                    </small>
                </h3>
            </div>
            <div class="panel-body">
                <div id="content">
                    <div id="about">
                        <h2>Welcome</h2>
                        <hr/>
                        <p>
                            Since you have made it this far, I must
                            confess there is nothing here.
                        </p>
                        <p>
                            Thanks for playing.
                        </p>            
                    </div>        
                </div>
            </div>
        </div>
        <a href="javascript:void(0);" class="a_credits" title="What?">
            <small class="pull-right text-muted">
                Kore9 version 0.<?=getVersion();?>
            </small>
        </a>
    </div>
</div>