<div class="">
	<div>
	    <h2>
	    	About Kore9
	    	<small>v<?=getVersion();?></small>
	    </h2>
	    <hr/>
	</div>
	<div>
		<p>
			Well, the truth is that we don't know what this is all about. 
			But you'll be the first one we tell when we figure such things
			out.
		</p>
		<p>
			Until then.
		</p>
	</div>
	<div>
		<p>
			<a href="javascript:void(0);" title="Wait, what?" class="a_credits">
				Who is responsible for this nonsense?
			</a>
		</p>
	</div>
	<button type="button" class="pull-right cancel btn btn-inverse" title="Retreat!">Go Back</button>
</div>