<div class="space"></div>
<div class="container">
    <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="title lg text-muted">
                    Kore9
                    <small class="pull-right">
                        <a href="javascript:void(0);" class="a_signin" title="I am not a Guest">
                            <span class="lg glyphicon glyphicon-lock"></span>
                        </a>
                    </small>
                </h3>
            </div>
            <div class="panel-body">
                <div id="signin">
                    <div id="register">
                        <div id="about">
                            <h2>Welcome Guest</h2>
                            <hr/>
                            <div>
                                <small>
                                    <a title="Being a Guest never got me anywhere..."class="a_register pull-left" href="javascript:void(0);">
                                        I don't want to be a guest anymore
                                    </a>
                                    <a title="I have problems making descisions about these things..." class="a_about pull-right" href="javascript:void(0);">
                                        I need to know what this is all about
                                    </a>
                                </small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <a href="javascript:void(0);" class="a_credits" title="What?">
            <small class="pull-right text-muted">
                Kore9 version <?=getVersion();?>
            </small>
        </a>
    </div>
</div>